from building import *
import os

cwd = GetCurrentDir()
src = []

src = Glob('*.c')

path =  [cwd]

group = DefineGroup('test', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')