from building import *
import os
import glob

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src = []

src += glob.glob('*.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
