from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src = []

src += ['protocol.c']
src += ['button.c']
src += ['hardware_interface.c']
src += ['channel.c']
src += ['device_type.c']
src += ['main.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
